-- 물고기 종류 별로 가장 큰 물고기의 ID, FISH_NAME, LENGTH 출력
-- ORDER BY ID ASC
-- 단, 가장 큰 물고기는 1마리만 있고 10cm 이하의 물고기가 가장 큰 경우는 없음

WITH RANKED_FISH AS (
    SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH, RANK() OVER(
        PARTITION BY FI.FISH_TYPE
        ORDER BY FI.LENGTH DESC
    ) AS LENGTH_RANK
    FROM FISH_INFO AS FI
    LEFT JOIN FISH_NAME_INFO AS FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
    ORDER BY FI.ID ASC
)

SELECT RF.ID, RF.FISH_NAME, RF.LENGTH
FROM RANKED_FISH AS RF
WHERE RF.LENGTH_RANK = 1
;