-- 부서별 평균 연봉 조회
-- SELECT DEPT_ID, DEPT_NAME_EN, AVG(SAL) AS AVG_SAL
-- ORDER BY AVG_SAL DESC

SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS HD
INNER JOIN HR_EMPLOYEES AS HE
ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY HD.DEPT_ID
ORDER BY AVG_SAL DESC
;