-- [문제 정보]
-- 평균 길이가 33cm 이상인 물고기들을 종류별로 분류하여 잡은 수, 최대 길이, 물고기의 종류 출력
-- 잡은 물고기의 길이가 10cm 이하이면 LENGTH가 NULL이다.
-- SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
-- ORDER BY FISH_TYPE ASC

WITH LENGTH_NOT_NULL AS (
SELECT (CASE
    WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH
    END
    )
FROM FISH_INFO
)

SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(CASE
    WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH
    END
    ) >= 33
ORDER BY FISH_TYPE ASC
;
